### ISSUE TITLE
Unable to exchange code for token

### ISSUE THREAD

**Issue by mrochon** [Azure-Samples/ms-identity-msal-java-samples#28]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

1. Deploy app locally as per instructions.
2. Register in AAD as per instructions
3. Run localhost:8080 and request sign in
4. Complete sign
5. Get error response from app: [invalid_token_response] An error occurred while attempting to retrieve the OAuth 2.0 Access Token Response: 401 Unauthorized: [no body]

Attempted to fix by modifying the initial token request to AAD by adding 'response_mode=form_post'. That results in the application raising 403 error, presumably because the 'http://localhost:8080/login/oauth2/code/ ' endpoint does not accept POST requests.
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by DidunAyodeji** [comment]
Hello. Could you please tell me which sample the customer was trying to run?

**Comment by bgavrilMS** [comment]
No reply from customer.

**Comment by iAMSagar44** [comment]
I am facing the same issue. Following the /4-spring-web-app/1-Authentication/sign-in sample.
Can you please re-open this issue?
